apiVersion: v1
kind: Service
metadata:
  name: ls-vision-service
spec:
  selector:
    app: ls-vision-pod-ui
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8000
  type: NodePort 
